# agents/rag_dspy_cpp_agent.py
import dspy
from rag.aosp_retriever import AOSPRetriever
from dspy_opt.hal_signatures import ModernCppVehicleHardwareSignature, CppVehicleAssertions

# Queries targeting domain helper class patterns — NOT aggregator or entry point
_QUERIES = [
    "VehicleHalService domain getAllPropertyConfigs VehiclePropConfig "
    "automotive vehicle helper class implementation",
    "GetValueRequest GetValueResult SetValueRequest SetValueResult "
    "VehiclePropValue automotive vehicle domain service",
    "FakeVehicleHardware getAllPropertyConfigs VehiclePropConfig "
    "areaConfigs automotive vehicle implementation domain",
    "VehiclePropConfig prop access changeMode getAllPropertyConfigs "
    "vector VehiclePropertyAccess VehiclePropertyChangeMode",
]

# Contract injected into every domain cpp generation.
# Domain agents generate VehicleHalService{Domain} helper class ONLY.
# VssVehicleHardware aggregator + main() are generated by VssGlueAgent.
_CONTRACT = """
=== Android 14 AIDL VHAL — Domain Service Class Contract ===

YOUR JOB: Generate VehicleHalService{Domain} — a domain helper class.
NOT your job: VssVehicleHardware, DefaultVehicleHal, main(), Android.bp.

ARCHITECTURE:
  [This agent]   → VehicleHalService{Domain}  (domain helper, no HAL subclass)
  [VssGlueAgent] → VssVehicleHardware : public IVehicleHardware  (aggregator)
  [VssGlueAgent] → VssVehicleService.cpp  (main entry point)
  [VssGlueAgent] → Android.bp  (single binary, all domains)

REQUIRED HEADER (VehicleHalService{Domain}.h):
  #pragma once
  #include <aidl/android/hardware/automotive/vehicle/VehiclePropConfig.h>
  #include <aidl/android/hardware/automotive/vehicle/GetValueRequest.h>
  #include <aidl/android/hardware/automotive/vehicle/GetValueResult.h>
  #include <aidl/android/hardware/automotive/vehicle/SetValueRequest.h>
  #include <aidl/android/hardware/automotive/vehicle/SetValueResult.h>
  #include <vector>

  namespace android::hardware::automotive::vehicle {
  namespace aidlvhal = ::aidl::android::hardware::automotive::vehicle;

  class VehicleHalService{Domain} {
  public:
      std::vector<aidlvhal::VehiclePropConfig> getAllPropertyConfigs() const;
      void getValues(const std::vector<aidlvhal::GetValueRequest>& requests,
                     std::vector<aidlvhal::GetValueResult>& results) const;
      void setValues(const std::vector<aidlvhal::SetValueRequest>& requests,
                     std::vector<aidlvhal::SetValueResult>& results);
      bool handlesProperty(int32_t propId) const;
  };
  }  // namespace android::hardware::automotive::vehicle

REQUIRED IMPL (VehicleService{Domain}.cpp):
  - getAllPropertyConfigs(): return stub VehiclePropConfig list for this domain
    (prop IDs are placeholders — VssGlueAgent assigns correct 32-bit AAOS IDs)
  - getValues(): for each req matching this domain, push GetValueResult{OK, value=0}
  - setValues(): accept requests, push SetValueResult{OK}
  - handlesProperty(): iterate getAllPropertyConfigs(), return true if prop found

FORBIDDEN — causes linker errors or build failure:
  VssVehicleHardware        — aggregator, NOT this agent's job
  IVehicleHardware          — do NOT subclass, domain class is a helper only
  DefaultVehicleHal         — used only by VssGlueAgent main()
  AServiceManager_addService — entry point, NOT here
  main()                    — NOT here
  Android.bp                — NOT here
  #include <hidl/>          — HIDL, wrong for Android 14
  Return<>, HIDL_FETCH_*    — HIDL types
  markdown fences (no ```cpp)
"""


class RagDspyCppAgent:
    def __init__(self, retriever=None, rag_db_path="rag/chroma_db", rag_top_k=8, **kwargs):
        self.retriever  = retriever or AOSPRetriever(db_path=rag_db_path)
        self.top_k      = rag_top_k
        self.predictor  = dspy.ChainOfThought(ModernCppVehicleHardwareSignature)
        self.assertions = CppVehicleAssertions(strict=False)

    def generate(
        self,
        domain:        str,
        properties:    str,
        extra_context: str = "",
    ) -> dict:
        # Always retrieve with all 4 vehicle-anchored queries
        retrieved     = self.retriever.retrieve_multi(_QUERIES, agent_type="cpp",
                                                      top_k=self.top_k)
        retrieved_text = "\n\n".join(
            doc.get("text", doc.get("page_content", "")) for doc in retrieved
        )

        # Always combine: contract + RAG + any repair/extra context
        # Never use "or" — repair must have BOTH violation feedback AND RAG grounding
        aosp_context = _CONTRACT + "\n" + retrieved_text
        if extra_context:
            aosp_context = extra_context + "\n" + aosp_context

        result = self.predictor(
            domain       = domain,
            properties   = properties,
            aosp_context = aosp_context,
        )
        result = self.assertions(result)

        return {
            "header":     getattr(result, "cpp_header", "") or "",
            "impl":       getattr(result, "cpp_impl",   "") or "",
            "reasoning":  getattr(result, "reasoning",  "") or "",
            "violations": getattr(result, "violations", []),
        }

    def _generate(self, domain: str, properties: str, aosp_context: str = "", **kwargs) -> str:
        """Alias for C4 retry engine — returns impl string, not dict."""
        out = self.generate(domain=domain, properties=properties,
                            extra_context=aosp_context)
        return out.get("impl", "")

    def repair(
        self,
        previous_output: dict,
        violations:      list,
        domain:          str,
        properties:      str,
    ) -> dict:
        summary = "\n".join(f"  [{i+1}] {v}" for i, v in enumerate(violations))
        extra   = (
            f"=== REPAIR — fix ALL violations before anything else ===\n"
            f"{summary}\n"
            f"Regenerate complete files. Do not repeat any violation.\n"
            f"=== END REPAIR ==="
        )
        return self.generate(domain, properties, extra_context=extra)


class RAGDSPyCppAgent:
    """Thin wrapper for RAGDSPyArchitectAgent and C4 retry engine compatibility."""

    def __init__(self, **kwargs):
        self.inner = RagDspyCppAgent(**kwargs)

    def run(self, module_spec) -> str:
        """Called by architect — returns impl string (not dict)."""
        out = self.inner.generate(
            domain     = module_spec.domain,
            properties = module_spec.to_llm_spec(),
        )
        return out.get("impl", "")

    def _generate(self, domain: str, properties: str,
                  aosp_context: str = "", **kwargs) -> str:
        """Called by C4 retry engine."""
        return self.inner._generate(domain=domain, properties=properties,
                                    aosp_context=aosp_context)