"""agents/vss_glue_agent.py
VSS Glue Agent — runs AFTER all domain agents complete.
"""

from __future__ import annotations
import glob
import logging
import os
import re
from typing import Optional

logger = logging.getLogger(__name__)

BINARY_NAME = "android.hardware.automotive.vehicle@V3-vss-service"
SERVICE_NAME = "vendor.vehicle-hal-vss"
INSTANCE = "android.hardware.automotive.vehicle.IVehicle/default"

DOMAINS = ["adas", "body", "cabin", "chassis", "hvac", "infotainment", "powertrain"]

_VSS_GROUP = 0x20000000
_VSS_AREA  = 0x01000000
_GLOBAL_IDX_START = 0x1000

_TYPE_BITS = {
    "BOOLEAN": 0x00200000,
    "INT":     0x00400000,
    "FLOAT":   0x00600000,
    "STRING":  0x00100000,
    "BYTES":   0x00700000,
    "INT64":   0x00500000,
}
_TYPE_DEFAULT = 0x00e00000


def _build_full_prop_id(global_idx: int, vtype: str) -> int:
    type_bits = _TYPE_BITS.get(vtype, _TYPE_DEFAULT)
    return _VSS_GROUP | _VSS_AREA | type_bits | (global_idx & 0xFFFF)


def _parse_aidl_properties(aidl_dir: str) -> list[dict]:
    props = []
    pattern = re.compile(
        r"^\s+(\w+)\s*=\s*(0x[0-9a-fA-F]+|\d+),\s*//\s*(\w+)(?:,\s*(\w+))?",
        re.MULTILINE,
    )

    aidl_files = sorted(glob.glob(os.path.join(aidl_dir, "VehicleProperty*.aidl")))
    global_idx = _GLOBAL_IDX_START

    for f in aidl_files:
        content = open(f, errors="ignore").read()
        for m in pattern.finditer(content):
            name = m.group(1)
            vtype = m.group(3) or "INT"
            access = m.group(4) or "READ_WRITE"
            full_id = _build_full_prop_id(global_idx, vtype)
            props.append({
                "name": name,
                "prop_id": hex(full_id),
                "type": vtype,
                "access": access
            })
            global_idx += 1

    logger.info(f"[VssGlueAgent] Parsed {len(props)} properties from {len(aidl_files)} AIDL files")
    return props


def _generate_vss_hardware_h() -> str:
    return """#pragma once
// Generated by VssGlueAgent — DO NOT EDIT
#include <IVehicleHardware.h>
#include <VehicleHalTypes.h>
#include <vector>
#include <unordered_map>

namespace android::hardware::automotive::vehicle {
using namespace aidl::android::hardware::automotive::vehicle;

class VssVehicleHardware : public IVehicleHardware {
public:
    VssVehicleHardware();
    ~VssVehicleHardware() override = default;

    std::vector<VehiclePropConfig> getAllPropertyConfigs() const override;
    StatusCode getPropConfigs(const std::vector<int32_t>& props,
                              std::vector<VehiclePropConfig>* outConfigs);
    StatusCode setValues(std::shared_ptr<const SetValuesCallback> callback,
                         const std::vector<SetValueRequest>& requests) override;
    StatusCode getValues(std::shared_ptr<const GetValuesCallback> callback,
                         const std::vector<GetValueRequest>& requests) const override;
    DumpResult dump(const std::vector<std::string>&) override;
    StatusCode checkHealth() override;
    void registerOnPropertyChangeEvent(std::unique_ptr<const PropertyChangeCallback>) override;
    void registerOnPropertySetErrorEvent(std::unique_ptr<const PropertySetErrorCallback>) override;

private:
    std::vector<int32_t> mPropIds;
    std::vector<std::unique_ptr<IVehicleHardware>> mDomainServices;
    mutable std::unordered_map<int32_t, VehiclePropValue> mStore;
};
} // namespace android::hardware::automotive::vehicle
"""


def _parse_class_name(header_content: str) -> str:
    """Parse class name from generated header — works regardless of LLM naming."""
    m = re.search(r'class\s+(\w+)\s*:\s*public\s+IVehicleHardware', header_content)
    return m.group(1) if m else None


def _generate_vss_hardware_cpp(props: list[dict], domains: list[str] = None,
                                domain_headers: dict[str, str] = None) -> str:
    """VssVehicleHardware holds array of IVehicleHardware domain services.
    Class names are parsed from generated headers — LLM naming does not matter.
    Fallback: use AIDL-parsed prop IDs if domain services return empty.
    """
    init_lines = "\n    ".join(f"mPropIds.push_back({p['prop_id']});" for p in props)

    _domains = domains if domains else DOMAINS
    _headers = domain_headers or {}

    # Parse actual class names from generated headers
    domain_class_map = {}
    for d in _domains:
        hdr = _headers.get(d, "")
        cls = _parse_class_name(hdr) if hdr else f"VehicleHalService{d.capitalize()}"
        domain_class_map[d] = cls

    domain_includes = "\n".join(
        f'#include "VehicleHalService{d.capitalize()}.h"' for d in _domains
    )

    # Array of IVehicleHardware — class name agnostic
    make_uniques = "\n    ".join(
        f'mDomainServices.push_back(std::make_unique<{cls}>());' 
        for d, cls in domain_class_map.items()
    )

    domain_configs = """    for (auto& svc : mDomainServices) {
        auto svc_cfgs = svc->getAllPropertyConfigs();
        configs.insert(configs.end(), svc_cfgs.begin(), svc_cfgs.end());
    }"""

    return f"""// Generated by VssGlueAgent — DO NOT EDIT
// Aggregates domain VehicleHalService* implementations (each extends IVehicleHardware)
#include "VssVehicleHardware.h"
{domain_includes}
#include <android-base/logging.h>

namespace android::hardware::automotive::vehicle {{
using namespace aidl::android::hardware::automotive::vehicle;

VssVehicleHardware::VssVehicleHardware() {{
    mPropIds.reserve({len(props)});
    {init_lines}
    // Load domain services via IVehicleHardware interface
    {make_uniques}
    LOG(INFO) << "[VSS] Loaded " << mPropIds.size() << " props, "
              << mDomainServices.size() << " domain services";
}}

static VehiclePropConfig makeConfig(int32_t propId) {{
    VehiclePropConfig cfg;
    cfg.prop = propId;
    cfg.access = VehiclePropertyAccess::READ_WRITE;
    cfg.changeMode = VehiclePropertyChangeMode::ON_CHANGE;
    cfg.areaConfigs = {{ {{.areaId = 0}} }};
    return cfg;
}}

std::vector<VehiclePropConfig> VssVehicleHardware::getAllPropertyConfigs() const {{
    std::vector<VehiclePropConfig> configs;
{domain_configs}
    // Fallback: if domain services return empty, use AIDL-parsed prop IDs
    if (configs.empty()) {{
        for (int32_t id : mPropIds) configs.push_back(makeConfig(id));
    }}
    LOG(INFO) << "[VSS] Registered " << configs.size() << " VSS properties";
    return configs;
}}

StatusCode VssVehicleHardware::getPropConfigs(
        const std::vector<int32_t>& props,
        std::vector<VehiclePropConfig>* outConfigs) {{
    outConfigs->clear();
    for (int32_t p : props) outConfigs->push_back(makeConfig(p));
    return StatusCode::OK;
}}

StatusCode VssVehicleHardware::setValues(
        std::shared_ptr<const SetValuesCallback> callback,
        const std::vector<SetValueRequest>& requests) {{
    std::vector<SetValueResult> results;
    for (const auto& r : requests) {{
        mStore[r.value.prop] = r.value;
        results.push_back({{.requestId = r.requestId, .status = StatusCode::OK}});
    }}
    (*callback)(results);
    return StatusCode::OK;
}}

StatusCode VssVehicleHardware::getValues(
        std::shared_ptr<const GetValuesCallback> callback,
        const std::vector<GetValueRequest>& requests) const {{
    std::vector<GetValueResult> results;
    for (const auto& r : requests) {{
        auto it = mStore.find(r.prop.prop);
        if (it != mStore.end()) {{
            results.push_back({{.requestId = r.requestId,
                               .status = StatusCode::OK,
                               .prop = it->second}});
        }} else {{
            VehiclePropValue val;
            val.prop = r.prop.prop;
            val.areaId = r.prop.areaId;
            val.value.int32Values = {{0}};
            results.push_back({{.requestId = r.requestId,
                               .status = StatusCode::OK,
                               .prop = val}});
        }}
    }}
    (*callback)(results);
    return StatusCode::OK;
}}

DumpResult VssVehicleHardware::dump(const std::vector<std::string>&) {{ return {{}}; }}
StatusCode VssVehicleHardware::checkHealth() {{ return StatusCode::OK; }}
void VssVehicleHardware::registerOnPropertyChangeEvent(std::unique_ptr<const PropertyChangeCallback>) {{}}
void VssVehicleHardware::registerOnPropertySetErrorEvent(std::unique_ptr<const PropertySetErrorCallback>) {{}}
}} // namespace
"""


def _generate_service_main() -> str:
    return f"""// Generated by VssGlueAgent — DO NOT EDIT
#include "VssVehicleHardware.h"
#include <DefaultVehicleHal.h>
#include <android/binder_manager.h>
#include <android/binder_process.h>
#include <android/log.h>
#include <memory>

#define LOG_TAG "VssVhal"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

using namespace android::hardware::automotive::vehicle;

int main() {{
    LOGI("VSS VHAL starting...");
    ABinderProcess_setThreadPoolMaxThreadCount(8);
    ABinderProcess_startThreadPool();

    auto hw = std::make_unique<VssVehicleHardware>();
    auto configs = hw->getAllPropertyConfigs();
    LOGI("VSS VHAL: %zu properties registered", configs.size());

    auto vhal = ndk::SharedRefBase::make<DefaultVehicleHal>(std::move(hw));
    const std::string instance = "{INSTANCE}";
    auto status = AServiceManager_addService(vhal->asBinder().get(), instance.c_str());

    if (status != STATUS_OK) {{
        LOGE("VSS VHAL: Failed to register, status=%d", status);
        return 1;
    }}
    LOGI("VSS VHAL: Registered as %s", instance.c_str());
    ABinderProcess_joinThreadPool();
    return 0;
}}
"""


def _generate_android_bp(impl_dir: Optional[str] = None, domains: list[str] = None) -> str:
    _domains = domains if domains else DOMAINS
    domain_srcs = "\n        ".join(
        f'"VehicleHalService{d.capitalize()}.cpp",' for d in _domains
    )
    return f"""package {{
    default_applicable_licenses: ["Android-Apache-2.0"],
}}

cc_library_static {{
    name: "VssVehicleHardware",
    vendor: true,
    defaults: ["VehicleHalDefaults"],
    srcs: [
        "VssVehicleHardware.cpp",
        {domain_srcs}
    ],
    header_libs: ["IVehicleHardware", "VehicleHalUtilHeaders"],
    export_include_dirs: ["."],
}}

cc_binary {{
    name: "{BINARY_NAME}",
    vendor: true,
    defaults: ["VehicleHalDefaults"],
    relative_install_path: "hw",
    srcs: ["VssVehicleService.cpp"],
    init_rc: ["{BINARY_NAME}.rc"],
    vintf_fragments: ["manifest_vss.xml"],
    static_libs: [
        "VssVehicleHardware",
        "DefaultVehicleHal",
        "VehicleHalUtils",
    ],
    shared_libs: [
        "libbinder_ndk",
        "libbase",
        "liblog",
        "libutils",
    ],
    header_libs: ["IVehicleHardware"],
}}
"""


def _generate_init_rc() -> str:
    return f"""service {SERVICE_NAME} /vendor/bin/hw/{BINARY_NAME}
    class hal
    user vehicle_network
    group vehicle_network system inet
    capabilities BLOCK_SUSPEND
    ioprio be 4
"""


def _generate_vss_te() -> str:
    return """type hal_vehicle_vss, domain;
type hal_vehicle_vss_exec, exec_type, vendor_file_type, file_type;
init_daemon_domain(hal_vehicle_vss)
hal_server_domain(hal_vehicle_vss, hal_vehicle)
binder_use(hal_vehicle_vss)
binder_call(hal_vehicle_vss, system_server)
binder_call(system_server, hal_vehicle_vss)
allow hal_vehicle_vss vndbinder_device:chr_file { read write open };
allow hal_vehicle_vss self:process { fork sigchld };
allow hal_vehicle_vss vendor_configs_file:dir search;
allow hal_vehicle_vss vendor_configs_file:file { read getattr open };
"""


def _generate_manifest() -> str:
    return """<manifest version="1.0" type="device">
    <hal format="aidl">
        <name>android.hardware.automotive.vehicle</name>
        <version>3</version>
        <fqname>IVehicle/default</fqname>
    </hal>
</manifest>
"""


class VssGlueAgent:
    def run(self, output_dir: str, aidl_dir: Optional[str] = None) -> dict[str, str]:
        os.makedirs(output_dir, exist_ok=True)

        props = _parse_aidl_properties(aidl_dir) if aidl_dir and os.path.isdir(aidl_dir) else []

        # Detect actual domains from generated AIDL files
        detected_domains = []
        if aidl_dir and os.path.isdir(aidl_dir):
            for f in sorted(glob.glob(os.path.join(aidl_dir, "VehicleProperty*.aidl"))):
                basename = os.path.basename(f)
                domain = basename.replace("VehicleProperty", "").replace(".aidl", "").lower()
                if domain:
                    detected_domains.append(domain)
        active_domains = detected_domains if detected_domains else DOMAINS
        logger.info(f"[VssGlueAgent] Active domains: {active_domains}")

        # Read generated domain headers for class name parsing
        domain_headers = {}
        if aidl_dir:
            impl_dir = os.path.join(os.path.dirname(os.path.dirname(aidl_dir)), "impl")
            for d in active_domains:
                h_path = os.path.join(impl_dir, f"VehicleHalService{d.capitalize()}.h")
                if os.path.exists(h_path):
                    domain_headers[d] = open(h_path, errors="ignore").read()

        artifacts = {
            "VssVehicleHardware.h":   _generate_vss_hardware_h(),
            "VssVehicleHardware.cpp": _generate_vss_hardware_cpp(props, active_domains, domain_headers),
            "VssVehicleService.cpp":  _generate_service_main(),
            "Android.bp":             _generate_android_bp(domains=active_domains),
            f"{BINARY_NAME}.rc":      _generate_init_rc(),
            "manifest_vss.xml":       _generate_manifest(),
            "vehicle_hal_vss.te":     _generate_vss_te(),
        }

        for filename, file_content in artifacts.items():
            with open(os.path.join(output_dir, filename), "w") as f:
                f.write(file_content)

        prop_count = len(props)
        logger.info(f"[VssGlueAgent] Generated {len(artifacts)} artifacts with {prop_count} properties")
        print(f"  [VssGlueAgent] ✓ {len(artifacts)} artifacts, {prop_count} VSS properties → {output_dir}")
        return artifacts

    def validate(self, output_dir: str) -> bool:
        required = ["VssVehicleHardware.h", "VssVehicleHardware.cpp", "VssVehicleService.cpp",
                    "Android.bp", f"{BINARY_NAME}.rc", "manifest_vss.xml"]
        missing = [f for f in required if not os.path.exists(os.path.join(output_dir, f))]
        if missing:
            logger.error(f"[VssGlueAgent] Missing files: {missing}")
            return False
        return True