"""
agents/vss_glue_agent.py
═══════════════════════════════════════════════════════════════
VSS Glue Agent — runs AFTER all domain agents complete.

Reads AIDL enum files generated by the pipeline and produces:
  - VssVehicleHardware.h    — Android 14 IVehicleHardware subclass
  - VssVehicleHardware.cpp  — getAllPropertyConfigs() with REAL 500 props
  - VehicleServiceMain.cpp  — AIDL V3 service entry point
  - Android.bp              — cc_library_static + cc_binary
  - manifest_vss.xml        — VINTF manifest with <interface> tags
  - *.rc                    — init.rc with correct binary name

Why deterministic (not LLM)?
  These artifacts depend on exact Android 14 API contracts that LLM
  cannot reliably reproduce (namespace, types, binary naming).
  The property configs are parsed from LLM-generated AIDL files.
═══════════════════════════════════════════════════════════════
"""

from __future__ import annotations

import glob
import logging
import os
import re
from typing import Optional

logger = logging.getLogger(__name__)

BINARY_NAME  = "android.hardware.automotive.vehicle@V3-vss-service"
SERVICE_NAME = "vendor.vehicle-vss"
INSTANCE     = "android.hardware.automotive.vehicle.IVehicle/default"

# Android 14 VehiclePropertyType bits for config generation
VHAL_TYPE_MAP = {
    "BOOLEAN": "VehiclePropertyType::BOOLEAN",
    "INT":     "VehiclePropertyType::INT32",
    "FLOAT":   "VehiclePropertyType::FLOAT",
    "STRING":  "VehiclePropertyType::STRING",
    "BYTES":   "VehiclePropertyType::BYTES",
    "INT64":   "VehiclePropertyType::INT64",
}

ACCESS_MAP = {
    "READ":       "VehiclePropertyAccess::READ",
    "WRITE":      "VehiclePropertyAccess::WRITE",
    "READ_WRITE": "VehiclePropertyAccess::READ_WRITE",
}


def _parse_aidl_properties(aidl_dir: str) -> list[dict]:
    """
    Parse property IDs, types, and access modes from generated AIDL enum files.
    Returns list of {name, prop_id, type, access, area} dicts.
    """
    props = []
    pattern = re.compile(
        r"(\w+)\s*=\s*(0x[0-9a-fA-F]+|\d+)"
        r"(?:\s*,\s*//\s*(BOOLEAN|INT|FLOAT|STRING|BYTES|INT64)?"
        r"(?:,\s*(READ|WRITE|READ_WRITE))?(?:,\s*(GLOBAL|VEHICLE))?)?",
        re.MULTILINE,
    )

    aidl_files = glob.glob(os.path.join(aidl_dir, "VehicleProperty*.aidl"))
    for f in sorted(aidl_files):
        content = open(f, errors="ignore").read()
        for m in pattern.finditer(content):
            name     = m.group(1)
            prop_id  = m.group(2)
            vtype    = m.group(3) or "INT"
            access   = m.group(4) or "READ_WRITE"
            area     = m.group(5) or "GLOBAL"
            props.append({
                "name": name,
                "prop_id": prop_id,
                "type": vtype,
                "access": access,
                "area": area,
            })

    logger.info(f"[VssGlueAgent] Parsed {len(props)} properties from {len(aidl_files)} AIDL files")
    return props


def _generate_vss_hardware_h() -> str:
    return """\
#pragma once
// Generated by VssGlueAgent — DO NOT EDIT
// Android 14 IVehicleHardware subclass for VSS VHAL.
#include <IVehicleHardware.h>
#include <VehicleHalTypes.h>
#include <vector>
#include <memory>
#include <functional>
#include <chrono>

namespace android::hardware::automotive::vehicle {

class VssVehicleHardware : public IVehicleHardware {
public:
    ~VssVehicleHardware() override = default;

    std::vector<aidl::android::hardware::automotive::vehicle::VehiclePropConfig>
            getAllPropertyConfigs() const override;

    aidl::android::hardware::automotive::vehicle::StatusCode setValues(
            std::shared_ptr<const SetValuesCallback> callback,
            const std::vector<aidl::android::hardware::automotive::vehicle::SetValueRequest>&
                    requests) override;

    aidl::android::hardware::automotive::vehicle::StatusCode getValues(
            std::shared_ptr<const GetValuesCallback> callback,
            const std::vector<aidl::android::hardware::automotive::vehicle::GetValueRequest>&
                    requests) const override;

    DumpResult dump(const std::vector<std::string>& options) override;
    aidl::android::hardware::automotive::vehicle::StatusCode checkHealth() override;
    void registerOnPropertyChangeEvent(
            std::unique_ptr<const PropertyChangeCallback> callback) override;
    void registerOnPropertySetErrorEvent(
            std::unique_ptr<const PropertySetErrorCallback> callback) override;
};

}  // namespace android::hardware::automotive::vehicle
"""


def _generate_vss_hardware_cpp(props: list[dict]) -> str:
    """Generate VssVehicleHardware.cpp with real property configs."""

    # Build getAllPropertyConfigs() body
    config_lines = []
    for p in props:
        prop_id = p["prop_id"]
        vtype   = VHAL_TYPE_MAP.get(p["type"], "VehiclePropertyType::INT32")
        access  = ACCESS_MAP.get(p["access"], "VehiclePropertyAccess::READ_WRITE")
        config_lines.append(
            f"    configs.push_back({{.prop = {prop_id},"
            f" .access = aidlvhal::{access.split('::')[1]},"
            f" .changeMode = aidlvhal::VehiclePropertyChangeMode::ON_CHANGE}});"
        )

    configs_body = "\n".join(config_lines) if config_lines else \
        "    // No properties parsed — check AIDL files in aidl_dir"

    return f"""\
// Generated by VssGlueAgent — DO NOT EDIT
// Implements Android 14 IVehicleHardware with {len(props)} VSS properties.
#include "VssVehicleHardware.h"

namespace android::hardware::automotive::vehicle {{

namespace aidlvhal = ::aidl::android::hardware::automotive::vehicle;

std::vector<aidlvhal::VehiclePropConfig> VssVehicleHardware::getAllPropertyConfigs() const {{
    std::vector<aidlvhal::VehiclePropConfig> configs;
    configs.reserve({len(props)});
{configs_body}
    return configs;
}}

aidlvhal::StatusCode VssVehicleHardware::setValues(
        std::shared_ptr<const SetValuesCallback> callback,
        const std::vector<aidlvhal::SetValueRequest>& requests) {{
    std::vector<aidlvhal::SetValueResult> results;
    for (const auto& req : requests) {{
        results.push_back({{.requestId = req.requestId,
                           .status = aidlvhal::StatusCode::OK}});
    }}
    (*callback)(std::move(results));
    return aidlvhal::StatusCode::OK;
}}

aidlvhal::StatusCode VssVehicleHardware::getValues(
        std::shared_ptr<const GetValuesCallback> callback,
        const std::vector<aidlvhal::GetValueRequest>& requests) const {{
    std::vector<aidlvhal::GetValueResult> results;
    for (const auto& req : requests) {{
        results.push_back({{.requestId = req.requestId,
                           .status = aidlvhal::StatusCode::OK}});
    }}
    (*callback)(std::move(results));
    return aidlvhal::StatusCode::OK;
}}

DumpResult VssVehicleHardware::dump(const std::vector<std::string>&) {{ return {{}}; }}

aidlvhal::StatusCode VssVehicleHardware::checkHealth() {{
    return aidlvhal::StatusCode::OK;
}}

void VssVehicleHardware::registerOnPropertyChangeEvent(
        std::unique_ptr<const PropertyChangeCallback>) {{}}

void VssVehicleHardware::registerOnPropertySetErrorEvent(
        std::unique_ptr<const PropertySetErrorCallback>) {{}}

}}  // namespace android::hardware::automotive::vehicle
"""


def _generate_service_main() -> str:
    return f"""\
// Generated by VssGlueAgent — DO NOT EDIT
// Android 14 AIDL VHAL V3 service entry point.
#include "VssVehicleHardware.h"
#include <DefaultVehicleHal.h>
#include <android/binder_manager.h>
#include <android/binder_process.h>
#include <memory>

using namespace android::hardware::automotive::vehicle;

int main() {{
    ABinderProcess_setThreadPoolMaxThreadCount(4);
    ABinderProcess_startThreadPool();

    auto hw = std::make_unique<VssVehicleHardware>();
    auto vhal = ndk::SharedRefBase::make<DefaultVehicleHal>(std::move(hw));
    const std::string instance = "{INSTANCE}";
    auto status = AServiceManager_addService(vhal->asBinder().get(), instance.c_str());
    if (status != STATUS_OK) {{
        return 1;
    }}
    ABinderProcess_joinThreadPool();
    return 0;
}}
"""


def _generate_android_bp() -> str:
    return f"""\
package {{
    default_applicable_licenses: ["Android-Apache-2.0"],
}}

// Generated by VssGlueAgent — Android 14 AIDL VHAL
cc_library_static {{
    name: "VssVehicleHardware",
    vendor: true,
    defaults: ["VehicleHalDefaults"],
    srcs: ["VssVehicleHardware.cpp"],
    header_libs: ["IVehicleHardware", "VehicleHalUtilHeaders"],
    export_include_dirs: ["."],
}}

cc_binary {{
    name: "{BINARY_NAME}",
    vendor: true,
    defaults: ["VehicleHalDefaults"],
    relative_install_path: "hw",
    srcs: ["VehicleServiceMain.cpp"],
    init_rc: ["{BINARY_NAME}.rc"],
    vintf_fragments: ["manifest_vss.xml"],
    static_libs: [
        "VssVehicleHardware",
        "DefaultVehicleHal",
        "VehicleHalUtils",
    ],
    shared_libs: [
        "libbinder_ndk",
        "libbase",
        "liblog",
        "libutils",
    ],
    header_libs: ["IVehicleHardware"],
}}
"""


def _generate_init_rc() -> str:
    return f"""\
service {SERVICE_NAME} /vendor/bin/hw/{BINARY_NAME}
    class hal
    user vehicle_network
    group system inet
    oneshot
"""


def _generate_manifest() -> str:
    return """\
<manifest version="1.0" type="device">
    <hal format="aidl">
        <name>android.hardware.automotive.vehicle</name>
        <version>3</version>
        <interface>
            <name>IVehicle</name>
            <instance>default</instance>
        </interface>
    </hal>
</manifest>
"""


class VssGlueAgent:
    """
    Generates deterministic Android 14 VHAL glue artifacts.
    Must run AFTER all domain agents have written their AIDL files.

    Usage:
        agent = VssGlueAgent()
        files = agent.run(
            output_dir="output_rag_dspy/.../impl/vss",
            aidl_dir="output_rag_dspy/.../aidl/.../vehicle",
        )
    """

    def run(self, output_dir: str, aidl_dir: Optional[str] = None) -> dict[str, str]:
        """
        Generate all glue artifacts.

        Parameters
        ----------
        output_dir : str
            Where to write VssVehicleHardware.h/.cpp, Android.bp etc.
            Typically: <output>/hardware/interfaces/automotive/vehicle/aidl/impl/vss/
        aidl_dir : str, optional
            Where to find VehicleProperty*.aidl files.
            Typically: <output>/hardware/interfaces/automotive/vehicle/aidl/.../vehicle/
            If None, getAllPropertyConfigs() will return empty (stub).
        """
        os.makedirs(output_dir, exist_ok=True)

        # Parse real properties from AIDL files
        props = []
        if aidl_dir and os.path.isdir(aidl_dir):
            props = _parse_aidl_properties(aidl_dir)
            logger.info(f"[VssGlueAgent] Using {len(props)} real VSS properties")
        else:
            logger.warning("[VssGlueAgent] No aidl_dir — getAllPropertyConfigs() will return empty")

        artifacts = {
            "VssVehicleHardware.h":    _generate_vss_hardware_h(),
            "VssVehicleHardware.cpp":  _generate_vss_hardware_cpp(props),
            "VehicleServiceMain.cpp":  _generate_service_main(),
            "Android.bp":              _generate_android_bp(),
            f"{BINARY_NAME}.rc":       _generate_init_rc(),
            "manifest_vss.xml":        _generate_manifest(),
        }

        for filename, content in artifacts.items():
            path = os.path.join(output_dir, filename)
            with open(path, "w") as f:
                f.write(content)

        prop_count = len(props)
        logger.info(
            f"[VssGlueAgent] Generated {len(artifacts)} artifacts "
            f"({prop_count} properties) → {output_dir}"
        )
        print(
            f"  [VssGlueAgent] ✓ {len(artifacts)} artifacts, "
            f"{prop_count} VSS properties in getAllPropertyConfigs()"
        )
        return artifacts

    def validate(self, output_dir: str) -> bool:
        required = [
            "VssVehicleHardware.h",
            "VssVehicleHardware.cpp",
            "VehicleServiceMain.cpp",
            "Android.bp",
            f"{BINARY_NAME}.rc",
            "manifest_vss.xml",
        ]
        missing = [f for f in required if not os.path.exists(os.path.join(output_dir, f))]
        if missing:
            logger.error(f"[VssGlueAgent] Missing: {missing}")
            return False
        return True